# Default initial positions for pr's ros2_control fake system

initial_positions:
  elbow_joint: 1.5708
  shoulder_lift_joint: -2.3562
  shoulder_pan_joint: 0
  wrist_1_joint: -0.7854
  wrist_2_joint: -1.5708
  wrist_3_joint: 0